### ISSUE TITLE
Demo credentials is wrong

### ISSUE THREAD

**Issue by ogunkarakus** [wallabag/wallabag.org#14]
Hi,

I'm want to try wallabag. But, unable to login with the demo user account.

User information (I tried):
* Username: *wallabag*
* Password: *wallabag*

Can you fix this issue?

Best regards, Ogün Karakuş

*Ping: @tcitworld*

**Comment by nicosomb** [comment]
I updated the demonstration website on our website: 

> These credentials may have changed, but don't worry: you can create a free account on this platform. Please remind that this website is a demonstration website and the database can be dropped at any time.
