### ISSUE TITLE
HTTPS RSS feed using insecure connection

### ISSUE THREAD

**Issue by Poorchop** [wallabag/wallabag.org#24]
I don't know much about RSS feeds but I'm not sure if SSL is configured properly for [wallabag's feed](https://www.wallabag.org/feeds/all.atom.xml). It always automatically redirects to https but the connection is insecure. I tried adding the feed to one of my RSS readers but I keep getting a handshake failure, including when I try to just fetch over regular http since is always redirects to https.

![untitled](https://cloud.githubusercontent.com/assets/5256208/15808960/d659993a-2b52-11e6-800a-046ce02bcb80.png)

**Comment by j0k3r** [comment]
Looks fine now
![image](https://cloud.githubusercontent.com/assets/62333/19033598/79dd5dc0-895f-11e6-8d9c-1a327ec340c1.png)

**Comment by nicosomb** [comment]
I close. If necessary, you can reopen.

**Comment by Poorchop** [comment]
Still having issues in Firefox 50.  
![untitled](https://cloud.githubusercontent.com/assets/5256208/20321682/4fa7f784-ab44-11e6-8387-3b765f7a9a6c.png)

I thought that I had tested shortly after I saw j0k3r's comment and it was fine at that time, although I could be remembering wrong. I was also able to add wallabag's feed to my RSS reader. Not sure what changed since then.

**Comment by nicosomb** [comment]
I just tried with Firefox Nightly and it seems OK. 

![capture d ecran 2016-11-15 a 21 06 59](https://cloud.githubusercontent.com/assets/121870/20321973/a27c184a-ab77-11e6-96a6-2c1295c95f44.png)

**Comment by Poorchop** [comment]
Tested on another computer and still having the same issue. Was a new certificate recently acquired? Maybe it just hasn't shipped with Firefox stable yet.

**Comment by nicosomb** [comment]
It's not a new certificate. 
I used the SSL from CloudFlare.

**Comment by j0k3r** [comment]
Could you please see the _additional information_ so we can have more information on what the certificat is wrong on your Firefox?

**Comment by Poorchop** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5256208/20322566/92b3e22e-ab47-11e6-9663-8d4f59837598.png)

**Comment by j0k3r** [comment]
Just tried: https://www.sslshopper.com/ssl-checker.html#hostname=https://www.wallabag.org/feeds/all.atom.xml
And it looks good.
What are your Firefox version?
What OS?

**Comment by Poorchop** [comment]
Tested in Firefox 49.0.2 and Firefox 50.
Tested both Firefox versions in both Windows 8.1 and OS X 10.11.
Also tried IE in Windows, which worked fine. Only having issues with Firefox stable.

**Comment by tcitworld** [comment]
What about Chrome ? Maybe click on « Repair Firefox » on `about:support`, this will remove all preferences and addons.

**Comment by Poorchop** [comment]
Works fine in latest Chromium build. I already tested in Firefox with addons disabled so I'm not sure if deleting my current profile is going to help. This is just on Firefox's end so hopefully this will be automatically resolved when Firefox 52 hits stable.

**Comment by tcitworld** [comment]
It works correctly for me with Firefox 49 on both GNU/Linux and Windows 10, unfortunately. So I'm not sure it will change anything for you.
