### ISSUE TITLE
Atom feed invalid: shows all entries as new on each update

### ISSUE THREAD

**Issue by azrdev** [wallabag/wallabag.org#25]
I've subscribed to the atom feed [1] with firefox dynamic bookmarks. Whenever there is a new entry in the feed, each of the previous entries appears again as new/unread.
Comparing with another feed revealed that wallabags feed is missing `<updated>` tags in each entry, which are mandatory according to the spec, see also the validation result [2]. I suspect the missing update dates are the reason for the annoying behaviour I observed.

[1] https://www.wallabag.org/feeds/all.atom.xml
[2] https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.wallabag.org%2Ffeeds%2Fall.atom.xml

**Comment by nicosomb** [comment]
I also use the RSS feeds and I don't have this problem. 

@tcitworld do you have this problem?

**Comment by tcitworld** [comment]
We use Pelican for the wallabag website, it should be tested with a blank Pelican website to see if this issue happens too and eventually file an issue upstream.

**Comment by azrdev** [comment]
following getpelican/pelican#2014 the issue is fixed after an upgrade of pelican which pulls feedgenerator v1.9

**Comment by nicosomb** [comment]
@azrdev Can you have a look if it's OK for you?

**Comment by azrdev** [comment]
@nicosomb it is, the `<updated>` tags are there, and judging from another pelican-generated feed this has the expected behaviour.
Thx for caring!
