### ISSUE TITLE
return 403 when using tor

### ISSUE THREAD

**Issue by pmaziere** [wallabag/wallabag.org#7]
When attempting to access the wallabag site via tor, the server return a 403 forbidden error.
Is that an official policy to forbid tor exit node to access your site, or is this a configuration issue ?

**Comment by tcitworld** [comment]
The website uses Github pages if I'm not mistaken, so maybe that's their policy. Need to convince @nicosomb to change that, then.

**Comment by nicosomb** [comment]
I like github pages, because I just have to commit on my repo, then Travis update our website. It's so easy for me to update our website and our documentation website. 

If you find a system like that, I can migrate.

**Comment by pmaziere** [comment]
Using tor to access github atom feeds return the right data.
I tried other sites hosted on github and they do not reject tor exit nodes, so I checked a little further: it seems that wallabag.org is using cloudflare, and there is a specific configuration in order to white-list tor  exit nodes: http://korben.info/cloudflare-tor-liste-blanche.html, but I guess this is out of your control if this is a github choice rather than yours

**Comment by tcitworld** [comment]
I thought Cloudflare asked for a captcha, my bad.

**Comment by pmaziere** [comment]
either you did something or it was an issue with a specific exit node, in any case data are now sometimes received  correctly

**Comment by nicosomb** [comment]
I didn't change our configuration ...
