### ISSUE TITLE
Write blog post about 1.9.1

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag.org#8]
Blog post about: 
* 1.9.1
* FirefoxOS application
* RMLL 2015 with link to the video / slides
* wallabag v2
* what else?

**Comment by tcitworld** [comment]
Perfect.

**Comment by nicosomb** [comment]
Idea from @marienfressinaud :-)

**Comment by marienfressinaud** [comment]
;)

**Comment by tcitworld** [comment]
*Draft, I'm finishing it after eating*

date: 2015-07-31 20:00:00+00:00
slug: wallabag-v1.9.1-released
title: wallabag v1.9.1 released, last version before v2 !

We are happy to announce you the release of wallabag v1.9.1. Unlike what it seems, it's quite an important version (it's just between 1.9 and 2.0). A whole number of bugs have been corrected, some translations added, many config websites files added, and there's also a handful of new features we hope you'll like.

##Features
* Buttons to go to next and previous article when you view an article.
* Button to mark article as read and go to next unread article.
* Keyboard shortcuts. Lots of them. And vim-style navigation. Check them out here.
* Gestures on touch screens. Swipe to left or right to navigate to next or previous articles.
* Toolbar also at the bottom of the article with baggy theme, you don't have to scroll back any more when finished !
* While you tag an article, you now see all the existing tags. Just click on them to add it to this article. And the more used are shown bigger.
* Mozilla Sharing Service ! You will need https to activate it, but it's worth the try, you can get rid of the old extension and use the build-in sharing from Firefox.
* Import *Netscape-formated-bookmarks*. This allows import of Firefox, Internet Explorer (I know, right !), Chrome browsers bookmarks. And certainly many other tools and applications.
* If you're using a reverse proxy, you might interested by the BASE_URL constant.

## Session issues
It's no secret that we've had kind of a hard deal to fix sessions issues. You always ended up disconnected after a while. The thing is, just a little configuration should get rid of this issues. Checkout the documentation there.

## wallabag v2

This is the end of wallabag [as we know it](https://www.youtube.com/watch?v=Z0GFRcFm-aY). ~~We launch our premium version~~ We get rid of the old code. We've rebuild wallabag using Symfony2 and it's now much better to work efficiently with clean code.

**Comment by nicosomb** [comment]
You can (must? ;-)) put this link into your post: https://github.com/wallabag/wallabag/issues/1254
